/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectoedii;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author clago
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        this.setSize(877, 551);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuArchivos = new javax.swing.JPopupMenu();
        jMNuevoArchivo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMAbrirArchivo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMGuardarArchivo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMSalirArchivo = new javax.swing.JMenuItem();
        pm_Campos = new javax.swing.JPopupMenu();
        Uno = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Dos = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        Tres = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        Cuatro = new javax.swing.JMenuItem();
        jd_crearCampos = new javax.swing.JDialog();
        jp_agregarCampo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jd_listarCampos = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jPrincipal = new javax.swing.JPanel();
        jPArchivos = new javax.swing.JPanel();
        jPA = new javax.swing.JPanel();
        jLArchivos = new javax.swing.JLabel();
        jPC = new javax.swing.JPanel();
        jLCampos = new javax.swing.JLabel();
        jPR = new javax.swing.JPanel();
        jLRegistros = new javax.swing.JLabel();
        jPI = new javax.swing.JPanel();
        jLIndices = new javax.swing.JLabel();
        jPE = new javax.swing.JPanel();
        jLEstandarizacion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLCerrar = new javax.swing.JLabel();
        jPA1 = new javax.swing.JPanel();
        jLArchivosNombre = new javax.swing.JLabel();

        jPopupMenuArchivos.setBackground(new java.awt.Color(0, 102, 102));
        jPopupMenuArchivos.setBorderPainted(false);
        jPopupMenuArchivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMNuevoArchivo.setText("Nuevo Archivo");
        jMNuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNuevoArchivoActionPerformed(evt);
            }
        });
        jPopupMenuArchivos.add(jMNuevoArchivo);
        jPopupMenuArchivos.add(jSeparator1);

        jMAbrirArchivo.setText("Abrir Archivo");
        jMAbrirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMAbrirArchivoMouseClicked(evt);
            }
        });
        jPopupMenuArchivos.add(jMAbrirArchivo);
        jPopupMenuArchivos.add(jSeparator2);

        jMGuardarArchivo.setText("Guardar Archivo");
        jPopupMenuArchivos.add(jMGuardarArchivo);
        jPopupMenuArchivos.add(jSeparator3);

        jMSalirArchivo.setText("Cerrar Archivo");
        jMSalirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirArchivoMouseClicked(evt);
            }
        });
        jPopupMenuArchivos.add(jMSalirArchivo);

        Uno.setText("Crear Campos");
        Uno.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                UnoMouseMoved(evt);
            }
        });
        Uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UnoMouseEntered(evt);
            }
        });
        Uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnoActionPerformed(evt);
            }
        });
        pm_Campos.add(Uno);
        pm_Campos.add(jSeparator4);

        Dos.setText("Listar Campos");
        Dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DosMouseClicked(evt);
            }
        });
        pm_Campos.add(Dos);

        jSeparator5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSeparator5MouseClicked(evt);
            }
        });
        pm_Campos.add(jSeparator5);

        Tres.setText("Modificar Campos");
        pm_Campos.add(Tres);
        pm_Campos.add(jSeparator6);

        Cuatro.setText("Borrar campos");
        pm_Campos.add(Cuatro);

        jp_agregarCampo.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Nombre del campo");

        jLabel2.setText("Longitud");

        jLabel3.setText("Tipo del campo");

        jLabel4.setText("LLave primaria");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CREAR CAMPOS");

        javax.swing.GroupLayout jp_agregarCampoLayout = new javax.swing.GroupLayout(jp_agregarCampo);
        jp_agregarCampo.setLayout(jp_agregarCampoLayout);
        jp_agregarCampoLayout.setHorizontalGroup(
            jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jp_agregarCampoLayout.setVerticalGroup(
            jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_crearCamposLayout = new javax.swing.GroupLayout(jd_crearCampos.getContentPane());
        jd_crearCampos.getContentPane().setLayout(jd_crearCamposLayout);
        jd_crearCamposLayout.setHorizontalGroup(
            jd_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jd_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_crearCamposLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp_agregarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jd_crearCamposLayout.setVerticalGroup(
            jd_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(jd_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_crearCamposLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp_agregarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LISTAR CAMPOS");

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jd_listarCamposLayout = new javax.swing.GroupLayout(jd_listarCampos.getContentPane());
        jd_listarCampos.getContentPane().setLayout(jd_listarCamposLayout);
        jd_listarCamposLayout.setHorizontalGroup(
            jd_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarCamposLayout.createSequentialGroup()
                .addGroup(jd_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listarCamposLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_listarCamposLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jd_listarCamposLayout.setVerticalGroup(
            jd_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarCamposLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPrincipal.setBackground(new java.awt.Color(0, 102, 102));
        jPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jPArchivos.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPArchivosLayout = new javax.swing.GroupLayout(jPArchivos);
        jPArchivos.setLayout(jPArchivosLayout);
        jPArchivosLayout.setHorizontalGroup(
            jPArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );
        jPArchivosLayout.setVerticalGroup(
            jPArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPrincipalLayout = new javax.swing.GroupLayout(jPrincipal);
        jPrincipal.setLayout(jPrincipalLayout);
        jPrincipalLayout.setHorizontalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addComponent(jPArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPrincipalLayout.setVerticalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 610, 460));

        jPA.setBackground(new java.awt.Color(0, 102, 102));
        jPA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLArchivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLArchivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLArchivos.setText("ARCHIVOS");
        jLArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLArchivosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPALayout = new javax.swing.GroupLayout(jPA);
        jPA.setLayout(jPALayout);
        jPALayout.setHorizontalGroup(
            jPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPALayout.setVerticalGroup(
            jPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 40));

        jPC.setBackground(new java.awt.Color(0, 102, 102));
        jPC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLCampos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCampos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCampos.setText("CAMPOS");
        jLCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCamposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCLayout = new javax.swing.GroupLayout(jPC);
        jPC.setLayout(jPCLayout);
        jPCLayout.setHorizontalGroup(
            jPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPCLayout.setVerticalGroup(
            jPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, 40));

        jPR.setBackground(new java.awt.Color(0, 102, 102));
        jPR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jLRegistros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLRegistros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRegistros.setText("REGISTROS");

        javax.swing.GroupLayout jPRLayout = new javax.swing.GroupLayout(jPR);
        jPR.setLayout(jPRLayout);
        jPRLayout.setHorizontalGroup(
            jPRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPRLayout.setVerticalGroup(
            jPRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 40));

        jPI.setBackground(new java.awt.Color(0, 102, 102));
        jPI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLIndices.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLIndices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIndices.setText("INDICES");

        javax.swing.GroupLayout jPILayout = new javax.swing.GroupLayout(jPI);
        jPI.setLayout(jPILayout);
        jPILayout.setHorizontalGroup(
            jPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLIndices, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPILayout.setVerticalGroup(
            jPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLIndices, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 40));

        jPE.setBackground(new java.awt.Color(0, 102, 102));
        jPE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLEstandarizacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLEstandarizacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEstandarizacion.setText("ESTANDARIZACIÓN");

        javax.swing.GroupLayout jPELayout = new javax.swing.GroupLayout(jPE);
        jPE.setLayout(jPELayout);
        jPELayout.setHorizontalGroup(
            jPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLEstandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPELayout.setVerticalGroup(
            jPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLEstandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 40));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCerrar.setText("X");
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 60, -1));

        jPA1.setBackground(new java.awt.Color(0, 102, 102));
        jPA1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), new java.awt.Color(0, 0, 0)));

        jLArchivosNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLArchivosNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPA1Layout = new javax.swing.GroupLayout(jPA1);
        jPA1.setLayout(jPA1Layout);
        jPA1Layout.setHorizontalGroup(
            jPA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPA1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLArchivosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPA1Layout.setVerticalGroup(
            jPA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPA1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLArchivosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jMNuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNuevoArchivoActionPerformed
        // TODO add your handling code here:
        if (archivo_temp == null) {
            jPopupMenuArchivos.setVisible(false);
            nuevo_archivo();
            jLArchivosNombre.setText(archivo_temp.getNombreArchivo());
        }else{
            JOptionPane.showMessageDialog(null, "Ya está abierto un Archivo");
        }
    }//GEN-LAST:event_jMNuevoArchivoActionPerformed

    private void jLArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLArchivosMouseClicked
        // TODO add your handling code here:
        jPopupMenuArchivos.setVisible(true);
        jPopupMenuArchivos.setLocation(380, 323);
    }//GEN-LAST:event_jLArchivosMouseClicked

    private void jMSalirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirArchivoMouseClicked
        // TODO add your handling code here:
        jPopupMenuArchivos.setVisible(false);
          if (archivo_temp != null) {
            int opcion = JOptionPane.showConfirmDialog(jPrincipal, "SEGURO QUE QUIERE CERRAR EL ARCHIVO", "Cerrar Archivo", JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                cerrarArchivo();
                jLArchivosNombre.setText(null);
            }
        } else {
            JOptionPane.showMessageDialog(jPrincipal, "No hay Archivos abiertos");
        }
    }//GEN-LAST:event_jMSalirArchivoMouseClicked

    private void jMAbrirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMAbrirArchivoMouseClicked
        // TODO add your handling code here:
        jPopupMenuArchivos.setVisible(false);
        if (archivo_temp == null) {
            
        }else{
            JOptionPane.showMessageDialog(this, "Ya hay un archivo abierto.");
        }
        
    }//GEN-LAST:event_jMAbrirArchivoMouseClicked

    private void jLCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCamposMouseClicked
        // TODO add your handling code here:
        pm_Campos.setVisible(true);
        pm_Campos.setLocation(380,450);
    }//GEN-LAST:event_jLCamposMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        pm_Campos.setVisible(false);
        jPopupMenuArchivos.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void UnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_UnoActionPerformed

    private void UnoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnoMouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_UnoMouseMoved

    private void UnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnoMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_UnoMouseEntered

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void UnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnoMouseClicked
        // TODO add your handling code here:
        jd_crearCampos.pack();
        jd_crearCampos.setLocationRelativeTo(this);
        jd_crearCampos.setModal(true);
        jd_crearCampos.setVisible(true);
    }//GEN-LAST:event_UnoMouseClicked

    private void jSeparator5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator5MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jSeparator5MouseClicked

    private void DosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DosMouseClicked
        // TODO add your handling code here:
          jd_listarCampos.pack();
        jd_listarCampos.setLocationRelativeTo(this);
        jd_listarCampos.setModal(true);
        jd_listarCampos.setVisible(true);
    }//GEN-LAST:event_DosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cuatro;
    private javax.swing.JMenuItem Dos;
    private javax.swing.JMenuItem Tres;
    private javax.swing.JMenuItem Uno;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLArchivos;
    private javax.swing.JLabel jLArchivosNombre;
    private javax.swing.JLabel jLCampos;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLEstandarizacion;
    private javax.swing.JLabel jLIndices;
    private javax.swing.JLabel jLRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMAbrirArchivo;
    private javax.swing.JMenuItem jMGuardarArchivo;
    private javax.swing.JMenuItem jMNuevoArchivo;
    private javax.swing.JMenuItem jMSalirArchivo;
    private javax.swing.JPanel jPA;
    private javax.swing.JPanel jPA1;
    private javax.swing.JPanel jPArchivos;
    private javax.swing.JPanel jPC;
    private javax.swing.JPanel jPE;
    private javax.swing.JPanel jPI;
    private javax.swing.JPanel jPR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenuArchivos;
    private javax.swing.JPanel jPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JDialog jd_crearCampos;
    private javax.swing.JDialog jd_listarCampos;
    private javax.swing.JPanel jp_agregarCampo;
    private javax.swing.JPopupMenu pm_Campos;
    // End of variables declaration//GEN-END:variables

    static Archivos archivo_temp;
    LinkedList<Nodo>listaEnlazada= new LinkedList<>();
    
    
private void nuevo_archivo() {
        JFileChooser jfc = new JFileChooser("./");

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt");
        jfc.setFileFilter(filtro);

        int result = jfc.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File archivoSelected = jfc.getSelectedFile();
            archivo_temp = new Archivos(archivoSelected.getName(), archivoSelected.getAbsolutePath() + ".txt");
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Se canceló la Operación.");
        }
}


    private void cerrarArchivo() {
        archivo_temp = null;
        
    }
public void agregarElementoAvailList(Nodo nuevoNodo){
    listaEnlazada.addFirst(nuevoNodo);
}
public void guardarAvailList(LinkedList<Nodo> lista, String archivo) {
        try (ObjectOutputStream stream = new ObjectOutputStream(new FileOutputStream(archivo))) {
            for (Nodo nodo : lista) {
                stream.writeObject(nodo);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
}
public LinkedList<Nodo> leerAvailList(String archivo) {
        LinkedList<Nodo> lista = new LinkedList<>();
        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream(archivo))) {
            while (true) {
                try {
                    Nodo nodo = (Nodo) in.readObject();
                    lista.add(nodo);
                } catch (EOFException e) {
                    break; // Fin del archivo
                }
            }
        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        return lista;
        
}

private void guardarMetadata() {
    // Asumimos que 'archivo_temp' es un objeto de la clase Archivos con la ruta y nombre del archivo
    if (archivo_temp != null) {
        // Crea el Metadata con el autor y el availList
        Metadata metadata = new Metadata("Autor Ejemplo", listaEnlazada);  // listaEnlazada es el availList

        // Guardar la metadata en un archivo
        metadata.guardarMetadata(archivo_temp.getPath() + ".meta");  // Guarda en un archivo con extensión .meta
    }
}
}


