/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyectoedii;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Color;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author clago
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        this.setSize(877, 551);
        jListCampos.setModel(new DefaultListModel<String>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuArchivos = new javax.swing.JPopupMenu();
        jMNuevoArchivo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMAbrirArchivo = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMGuardarArchivo = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMSalirArchivo = new javax.swing.JMenuItem();
        pm_Campos = new javax.swing.JPopupMenu();
        mi_CrearCampo = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mi_ListarCmpos = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mi_ModificarCampo = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mi_borrarCampo = new javax.swing.JMenuItem();
        jd_crearCampos = new javax.swing.JDialog();
        jp_agregarCampo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreCrear = new javax.swing.JTextField();
        tf_tamanio = new javax.swing.JTextField();
        cb_llave = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jb_crearCampo = new javax.swing.JButton();
        cb_tipoCampo = new javax.swing.JComboBox<>();
        jd_listarCampos = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        pm_modificar = new javax.swing.JPopupMenu();
        mi_modificarCampo = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mi_borrar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_NombreCampo = new javax.swing.JTextField();
        js_ModLongitud = new javax.swing.JSpinner();
        jb_modificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_modTipo = new javax.swing.JComboBox<>();
        pm_Registros = new javax.swing.JPopupMenu();
        mi_IntroducirRegstro = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mi_ModificarRegsitro = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mi_BuscarRegistro = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mi_EliminarRegistro = new javax.swing.JMenuItem();
        jd_IntroRegistro = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jd_IntroReg = new javax.swing.JScrollPane();
        jt_Introd = new javax.swing.JTable();
        jb_agregarRegistro = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPrincipal = new javax.swing.JPanel();
        jPArchivos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListCampos = new javax.swing.JList<>();
        jPA = new javax.swing.JPanel();
        jLArchivos = new javax.swing.JLabel();
        jPC = new javax.swing.JPanel();
        jLCampos = new javax.swing.JLabel();
        jPR = new javax.swing.JPanel();
        jLRegistros = new javax.swing.JLabel();
        jPI = new javax.swing.JPanel();
        jLIndices = new javax.swing.JLabel();
        jPE = new javax.swing.JPanel();
        jLEstandarizacion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLCerrar = new javax.swing.JLabel();
        jPA1 = new javax.swing.JPanel();
        jLArchivosNombre = new javax.swing.JLabel();

        jPopupMenuArchivos.setBackground(new java.awt.Color(0, 102, 102));
        jPopupMenuArchivos.setBorderPainted(false);
        jPopupMenuArchivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMNuevoArchivo.setText("Nuevo Archivo");
        jMNuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMNuevoArchivoActionPerformed(evt);
            }
        });
        jPopupMenuArchivos.add(jMNuevoArchivo);
        jPopupMenuArchivos.add(jSeparator1);

        jMAbrirArchivo.setText("Abrir Archivo");
        jMAbrirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMAbrirArchivoMouseClicked(evt);
            }
        });
        jMAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAbrirArchivoActionPerformed(evt);
            }
        });
        jPopupMenuArchivos.add(jMAbrirArchivo);
        jPopupMenuArchivos.add(jSeparator2);

        jMGuardarArchivo.setText("Guardar Archivo");
        jMGuardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGuardarArchivoActionPerformed(evt);
            }
        });
        jPopupMenuArchivos.add(jMGuardarArchivo);
        jPopupMenuArchivos.add(jSeparator3);

        jMSalirArchivo.setText("Cerrar Archivo");
        jMSalirArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirArchivoMouseClicked(evt);
            }
        });
        jMSalirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirArchivoActionPerformed(evt);
            }
        });
        jPopupMenuArchivos.add(jMSalirArchivo);

        pm_Campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pm_CamposMouseEntered(evt);
            }
        });

        mi_CrearCampo.setText("Crear Campos");
        mi_CrearCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_CrearCampoActionPerformed(evt);
            }
        });
        pm_Campos.add(mi_CrearCampo);
        pm_Campos.add(jSeparator4);

        mi_ListarCmpos.setText("Listar Campos");
        mi_ListarCmpos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ListarCmposActionPerformed(evt);
            }
        });
        pm_Campos.add(mi_ListarCmpos);

        jSeparator5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSeparator5MouseClicked(evt);
            }
        });
        pm_Campos.add(jSeparator5);

        mi_ModificarCampo.setText("Modificar Campos");
        mi_ModificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ModificarCampoActionPerformed(evt);
            }
        });
        pm_Campos.add(mi_ModificarCampo);
        pm_Campos.add(jSeparator6);

        mi_borrarCampo.setText("Borrar campos");
        mi_borrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_borrarCampoActionPerformed(evt);
            }
        });
        pm_Campos.add(mi_borrarCampo);

        jp_agregarCampo.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre del campo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Longitud");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tipo del campo");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Llave primaria");

        cb_llave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        cb_llave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_llaveActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CREAR CAMPOS");

        jb_crearCampo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jb_crearCampo.setText("CREAR");
        jb_crearCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_crearCampoActionPerformed(evt);
            }
        });

        cb_tipoCampo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entero", "Cadena", "Double", "Booleano" }));

        javax.swing.GroupLayout jp_agregarCampoLayout = new javax.swing.GroupLayout(jp_agregarCampo);
        jp_agregarCampo.setLayout(jp_agregarCampoLayout);
        jp_agregarCampoLayout.setHorizontalGroup(
            jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_crearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_tamanio, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(tf_nombreCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                    .addComponent(cb_llave, 0, 242, Short.MAX_VALUE)
                                    .addComponent(cb_tipoCampo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jp_agregarCampoLayout.setVerticalGroup(
            jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarCampoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_nombreCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tipoCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jp_agregarCampoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_llave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jb_crearCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_crearCamposLayout = new javax.swing.GroupLayout(jd_crearCampos.getContentPane());
        jd_crearCampos.getContentPane().setLayout(jd_crearCamposLayout);
        jd_crearCamposLayout.setHorizontalGroup(
            jd_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(jd_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_crearCamposLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp_agregarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jd_crearCamposLayout.setVerticalGroup(
            jd_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
            .addGroup(jd_crearCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_crearCamposLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp_agregarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LISTAR CAMPOS");

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jd_listarCamposLayout = new javax.swing.GroupLayout(jd_listarCampos.getContentPane());
        jd_listarCampos.getContentPane().setLayout(jd_listarCamposLayout);
        jd_listarCamposLayout.setHorizontalGroup(
            jd_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarCamposLayout.createSequentialGroup()
                .addGroup(jd_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_listarCamposLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_listarCamposLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jd_listarCamposLayout.setVerticalGroup(
            jd_listarCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarCamposLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        mi_modificarCampo.setText("Modificar");
        mi_modificarCampo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mi_modificarCampoMouseClicked(evt);
            }
        });
        mi_modificarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarCampoActionPerformed(evt);
            }
        });
        pm_modificar.add(mi_modificarCampo);
        pm_modificar.add(jSeparator7);

        mi_borrar.setText("Eliminar");
        mi_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_borrarActionPerformed(evt);
            }
        });
        pm_modificar.add(mi_borrar);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre del campo");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Longitud");

        jb_modificar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jb_modificar.setText("MODIFICAR");
        jb_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_modificarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MODIFICAR CAMPO");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tipo");

        cb_modTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entero", "Cadena", "Double", "Booleano" }));
        cb_modTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_modTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ModificarLayout = new javax.swing.GroupLayout(Modificar.getContentPane());
        Modificar.getContentPane().setLayout(ModificarLayout);
        ModificarLayout.setHorizontalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_NombreCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(js_ModLongitud)
                            .addComponent(cb_modTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ModificarLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        ModificarLayout.setVerticalGroup(
            ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_NombreCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_ModLongitud, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_modTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        mi_IntroducirRegstro.setText("Introducir Registros");
        mi_IntroducirRegstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_IntroducirRegstroActionPerformed(evt);
            }
        });
        pm_Registros.add(mi_IntroducirRegstro);
        pm_Registros.add(jSeparator8);

        mi_ModificarRegsitro.setText("Modificar Registro");
        pm_Registros.add(mi_ModificarRegsitro);
        pm_Registros.add(jSeparator9);

        mi_BuscarRegistro.setText("Buscar Registro");
        pm_Registros.add(mi_BuscarRegistro);
        pm_Registros.add(jSeparator10);

        mi_EliminarRegistro.setText("Eliminar registro");
        pm_Registros.add(mi_EliminarRegistro);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Nuevo Registro");

        jt_Introd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jt_Introd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jd_IntroReg.setViewportView(jt_Introd);

        jb_agregarRegistro.setText("AGREGAR");
        jb_agregarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_IntroRegistroLayout = new javax.swing.GroupLayout(jd_IntroRegistro.getContentPane());
        jd_IntroRegistro.getContentPane().setLayout(jd_IntroRegistroLayout);
        jd_IntroRegistroLayout.setHorizontalGroup(
            jd_IntroRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_IntroRegistroLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jd_IntroReg, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(jd_IntroRegistroLayout.createSequentialGroup()
                .addGroup(jd_IntroRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_IntroRegistroLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_IntroRegistroLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jb_agregarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_IntroRegistroLayout.setVerticalGroup(
            jd_IntroRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_IntroRegistroLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jd_IntroReg, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                .addComponent(jb_agregarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        jPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jPArchivos.setBackground(new java.awt.Color(204, 204, 204));

        jListCampos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListCampos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jListCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListCamposMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListCampos);

        javax.swing.GroupLayout jPArchivosLayout = new javax.swing.GroupLayout(jPArchivos);
        jPArchivos.setLayout(jPArchivosLayout);
        jPArchivosLayout.setHorizontalGroup(
            jPArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPArchivosLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPArchivosLayout.setVerticalGroup(
            jPArchivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPArchivosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPrincipalLayout = new javax.swing.GroupLayout(jPrincipal);
        jPrincipal.setLayout(jPrincipalLayout);
        jPrincipalLayout.setHorizontalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPrincipalLayout.createSequentialGroup()
                .addComponent(jPArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPrincipalLayout.setVerticalGroup(
            jPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 610, 460));

        jPA.setBackground(new java.awt.Color(204, 204, 204));
        jPA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLArchivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLArchivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLArchivos.setText("ARCHIVOS");
        jLArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLArchivosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPALayout = new javax.swing.GroupLayout(jPA);
        jPA.setLayout(jPALayout);
        jPALayout.setHorizontalGroup(
            jPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPALayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPALayout.setVerticalGroup(
            jPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLArchivos, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 40));

        jPC.setBackground(new java.awt.Color(204, 204, 204));
        jPC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLCampos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCampos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCampos.setText("CAMPOS");
        jLCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCamposMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCLayout = new javax.swing.GroupLayout(jPC);
        jPC.setLayout(jPCLayout);
        jPCLayout.setHorizontalGroup(
            jPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPCLayout.setVerticalGroup(
            jPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCampos, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, 40));

        jPR.setBackground(new java.awt.Color(204, 204, 204));
        jPR.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jLRegistros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLRegistros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLRegistros.setText("REGISTROS");
        jLRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLRegistrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPRLayout = new javax.swing.GroupLayout(jPR);
        jPR.setLayout(jPRLayout);
        jPRLayout.setHorizontalGroup(
            jPRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPRLayout.setVerticalGroup(
            jPRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, 40));

        jPI.setBackground(new java.awt.Color(204, 204, 204));
        jPI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLIndices.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLIndices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIndices.setText("INDICES");

        javax.swing.GroupLayout jPILayout = new javax.swing.GroupLayout(jPI);
        jPI.setLayout(jPILayout);
        jPILayout.setHorizontalGroup(
            jPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLIndices, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPILayout.setVerticalGroup(
            jPILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLIndices, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jPanel1.add(jPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 40));

        jPE.setBackground(new java.awt.Color(204, 204, 204));
        jPE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        jLEstandarizacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLEstandarizacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLEstandarizacion.setText("ESTANDARIZACIÓN");

        javax.swing.GroupLayout jPELayout = new javax.swing.GroupLayout(jPE);
        jPE.setLayout(jPELayout);
        jPELayout.setHorizontalGroup(
            jPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLEstandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPELayout.setVerticalGroup(
            jPELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPELayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLEstandarizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));

        jLCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jLCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCerrar.setText("X");
        jLCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 60, -1));

        jPA1.setBackground(new java.awt.Color(204, 204, 204));
        jPA1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), new java.awt.Color(0, 0, 0)));

        jLArchivosNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLArchivosNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPA1Layout = new javax.swing.GroupLayout(jPA1);
        jPA1.setLayout(jPA1Layout);
        jPA1Layout.setHorizontalGroup(
            jPA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPA1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLArchivosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPA1Layout.setVerticalGroup(
            jPA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPA1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLArchivosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLCerrarMouseClicked

    private void jMNuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMNuevoArchivoActionPerformed
        // TODO add your handling code here:
        if (archivo_temp == null) {
            jPopupMenuArchivos.setVisible(false);
            pm_Campos.setVisible(false);
            nuevo_archivo();
            jLArchivosNombre.setText(archivo_temp.getNombreArchivo());
        }else{
            JOptionPane.showMessageDialog(null, "Ya está abierto un Archivo");
        }
    }//GEN-LAST:event_jMNuevoArchivoActionPerformed

    private void jLArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLArchivosMouseClicked
        // TODO add your handling code here:
        jPopupMenuArchivos.show(evt.getComponent(), evt.getX(), evt.getY());
        pm_Campos.setVisible(false);
    }//GEN-LAST:event_jLArchivosMouseClicked

    private void jMSalirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirArchivoMouseClicked
        // TODO add your handling code here:
        jPopupMenuArchivos.setVisible(false);
        pm_Campos.setVisible(false);
          if (archivo_temp != null) {
            int opcion = JOptionPane.showConfirmDialog(jPrincipal, "SEGURO QUE QUIERE CERRAR EL ARCHIVO", "Cerrar Archivo", JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                cerrarArchivo();
                jLArchivosNombre.setText(null);
            }
        } else {
            JOptionPane.showMessageDialog(jPrincipal, "No hay Archivos abiertos");
        }
    }//GEN-LAST:event_jMSalirArchivoMouseClicked

    private void jMAbrirArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMAbrirArchivoMouseClicked
        // TODO add your handling code here:
        jPopupMenuArchivos.setVisible(false);
        pm_Campos.setVisible(false);
        if (archivo_temp == null) {
            abrirArchivo();
        }else{
            JOptionPane.showMessageDialog(this, "Ya hay un archivo abierto.");
        }
        
    }//GEN-LAST:event_jMAbrirArchivoMouseClicked

    private void jLCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCamposMouseClicked
        // TODO add your handling code here:
        pm_Campos.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jLCamposMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        pm_Campos.setVisible(false);
        jPopupMenuArchivos.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void mi_CrearCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_CrearCampoActionPerformed
        // TODO add your handling code here:
        
        pm_Campos.setVisible(false);
        jd_crearCampos.pack();
        jd_crearCampos.setLocationRelativeTo(this);
        jd_crearCampos.setModal(true);
        jd_crearCampos.setVisible(true);
    }//GEN-LAST:event_mi_CrearCampoActionPerformed

    private void jSeparator5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSeparator5MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jSeparator5MouseClicked

    private void jMGuardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGuardarArchivoActionPerformed
        // TODO add your handling code here:
        jPopupMenuArchivos.setVisible(false);
        pm_Campos.setVisible(false);
         if (archivo_temp != null) {
            // guardararchivo();
            archivo_temp.escribirCamposEnArchivo(archivo_temp.getPath());
        }else{
            JOptionPane.showMessageDialog(this, "Debe haber un archivo abierto.");
        }
       
    }//GEN-LAST:event_jMGuardarArchivoActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        pm_modificar.show(evt.getComponent(), evt.getX(), evt.getY());
        
    }//GEN-LAST:event_jList1MouseClicked

    private void mi_modificarCampoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mi_modificarCampoMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_mi_modificarCampoMouseClicked

    private void jListCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListCamposMouseClicked
        // TODO add your handling code here:
        if (jListCampos.getSelectedIndex() >= 0) {
           // pm_modificar.setVisible(true);
            pm_modificar.show(jListCampos, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jListCamposMouseClicked

    private void mi_modificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarCampoActionPerformed
        // TODO add your handling code here:
        tf_NombreCampo.setText(archivo_temp.getCampos().get(jListCampos.getSelectedIndex()).getNombre());
        //jSpinner1.setValue((int)archivo_temp.getCampos().get(jListCampos.getSelectedIndex()).getTam());
        Modificar.pack();
        Modificar.setLocationRelativeTo(this);
        Modificar.setModal(true);
        Modificar.setVisible(true);
        

    }//GEN-LAST:event_mi_modificarCampoActionPerformed

    private void mi_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_borrarActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jListCampos.getSelectedIndex();
        if (selectedIndex > -1) {
            System.out.println(archivo_temp.getCampos().get(selectedIndex).getLlave().equals("1"));
            if (archivo_temp.getCampos().get(selectedIndex).getLlave().equals("1")) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar la llave primaria");
            } else {
                archivo_temp.getCampos().remove(selectedIndex);
                actualizarListaCampos2();
                JOptionPane.showMessageDialog(null, "Elemento eliminado correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un elemento para eliminar");
        }
    }//GEN-LAST:event_mi_borrarActionPerformed

    private void jb_crearCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_crearCampoActionPerformed
        // TODO add your handling code here:
        if (tf_nombreCrear.getText().equals("") || tf_tamanio.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Hay un campo vacio");
        } else {
            Campos campo = new Campos();
            campo.setNombre(tf_nombreCrear.getText());
            campo.setTam(tf_tamanio.getText());
            String frase = devolverTipo(cb_tipoCampo);
            campo.setTipo((Object) frase);
            String key = "";
            boolean bandera = true;
            if (cb_llave.getSelectedIndex() == 0) {
                campo.setLlavePrimaria(bandera);
                if (hayLlavePrimaria(archivo_temp.getCampos())) {
                    JOptionPane.showMessageDialog(null, "Ya existe un campo como llave primaria");
                } else {
                    archivo_temp.getCampos().add(campo);

                    JOptionPane.showMessageDialog(null, "Campo agregado correctamente");
                    jd_crearCampos.setVisible(false);
                    tf_NombreCampo.setText("");
                    tf_tamanio.setText("");

                }

            } else {
                campo.setLlaveSecundaria(bandera);
                bandera = false;
                campo.setLlavePrimaria(bandera);
                archivo_temp.getCampos().add(campo);

                JOptionPane.showMessageDialog(null, "Campo agregado correctamente");
                jd_crearCampos.setVisible(false);
                tf_NombreCampo.setText("");
                tf_tamanio.setText("");
            }

        }
    }//GEN-LAST:event_jb_crearCampoActionPerformed

    private void mi_ListarCmposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ListarCmposActionPerformed
        // TODO add your handling code here:
//        jPopupMenuArchivos.setVisible(false);
//         pm_Campos.setVisible(false);
         actualizarListaCampos2();
//         jListCampos.setVisible(true);
    }//GEN-LAST:event_mi_ListarCmposActionPerformed

    private void mi_ModificarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ModificarCampoActionPerformed
        // TODO add your handling code here:
        if (archivo_temp.getCampos().size() == 0) {
            JOptionPane.showMessageDialog(this, "No hay campos para modificar");
        } else {
            if (jListCampos.getSelectedIndex() >= 0) {
                tf_NombreCampo.setText(archivo_temp.getCampos().get(jListCampos.getSelectedIndex()).getNombre());
                Modificar.pack();
                Modificar.setLocationRelativeTo(this);
                Modificar.setModal(true);
                Modificar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Primero seleccione un campo a modificar");
            }
        }
    }//GEN-LAST:event_mi_ModificarCampoActionPerformed

    private void pm_CamposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pm_CamposMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_pm_CamposMouseEntered

    private void jMAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAbrirArchivoActionPerformed
        // TODO add your handling code here:
        jPopupMenuArchivos.setVisible(false);
        pm_Campos.setVisible(false);
        if (archivo_temp == null) {
            abrirArchivo();
        }else{
            JOptionPane.showMessageDialog(this, "Ya hay un archivo abierto.");
        }
    }//GEN-LAST:event_jMAbrirArchivoActionPerformed

    private void mi_borrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_borrarCampoActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jListCampos.getSelectedIndex();
        if (selectedIndex > -1) {
            System.out.println(archivo_temp.getCampos().get(selectedIndex).getLlave().equals("1"));
            if (archivo_temp.getCampos().get(selectedIndex).getLlave().equals("1")) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar la llave primaria");
            } else {
                archivo_temp.getCampos().remove(selectedIndex);
                actualizarListaCampos2();
                JOptionPane.showMessageDialog(null, "Elemento eliminado correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un elemento para eliminar");
        }
    }//GEN-LAST:event_mi_borrarCampoActionPerformed

    private void jLRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLRegistrosMouseClicked
        // TODO add your handling code here:
        pm_Registros.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jLRegistrosMouseClicked

    private void cb_llaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_llaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_llaveActionPerformed

    private void jb_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_modificarActionPerformed
        // TODO add your handling code here:

        String nombre="";
        int tamanio=0;
        if (jListCampos.getSelectedIndex() >= 0) {
            nombre = tf_NombreCampo.getText();
            tamanio = (int) js_ModLongitud.getValue();
            Campos campoAux = (Campos) archivo_temp.getCampos().get(jListCampos.getSelectedIndex());
            campoAux.setNombre(nombre);
            campoAux.setTam(tamanio);
            String tipo=devolverTipo(cb_modTipo);
            campoAux.setTipo(tipo);
            if (campoAux != null) {
                archivo_temp.modificarCampo(campoAux, jListCampos.getSelectedIndex());
                actualizarListaCampos2();
                Modificar.setVisible(false);
                JOptionPane.showMessageDialog(this, "Campo modificado con exito");
            } else {
            }
        } else {
            JOptionPane.showMessageDialog(this, "Primero seleccione un campo a modificar");
        }
        

    }//GEN-LAST:event_jb_modificarActionPerformed

    private void cb_modTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_modTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_modTipoActionPerformed

    private void mi_IntroducirRegstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_IntroducirRegstroActionPerformed
        // TODO add your handling code here:
        jd_IntroRegistro.pack();
        jd_IntroRegistro.setLocationRelativeTo(this);
        jd_IntroRegistro.setModal(false);
        jd_IntroRegistro.setVisible(true);
        DefaultTableModel tableModel = new DefaultTableModel();
        
        String [] nombres=new String[archivo_temp.getCampos().size()];
        for (int i = 0; i < nombres.length; i++) {
            nombres[i]=archivo_temp.getCampos().get(i).getNombre();
        }
        tableModel.setColumnIdentifiers(nombres);
        for (int i = 0; i < 5; i++) {
            tableModel.addRow(new Object[nombres.length]); 
        }
        
        jt_Introd.setModel(tableModel);
        jt_Introd.setFillsViewportHeight(true);

        
    }//GEN-LAST:event_mi_IntroducirRegstroActionPerformed

    private void jb_agregarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarRegistroActionPerformed
        // TODO add your handling code here:
        int contador = 0;
        int contador2=0;
        for (int i = 0; i < jt_Introd.getRowCount(); i++) {
            boolean filaCompleta = true;
            ArrayList nueva = new ArrayList();

            for (int j = 0; j < jt_Introd.getColumnCount(); j++) {
                if (jt_Introd.getValueAt(i, j) == null || jt_Introd.getValueAt(i, j).toString().isEmpty()) {
                    filaCompleta = false;
                    contador++;
                    break;
                }
                if (filaCompleta) {

                    nueva.add(jt_Introd.getValueAt(i, j));
                    contador2++;

                }
            }
            Registro nuevo = new Registro();
            nuevo.setInformacion(nueva);//tengo un nuevo registro completo

        }
        if (contador == jt_Introd.getRowCount()) {
            JOptionPane.showMessageDialog(this, "Ingrese informacion de registros");
        } else {
            jd_IntroRegistro.setVisible(false);
            JOptionPane.showMessageDialog(this, contador+" Registros agregados con éxito");
        }
        
    }//GEN-LAST:event_jb_agregarRegistroActionPerformed

    private void jMSalirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirArchivoActionPerformed
        // TODO add your handling code here:
        archivo_temp=null;
        jLArchivosNombre.setText("");
        JOptionPane.showMessageDialog(this, "Archivo cerrado");
    }//GEN-LAST:event_jMSalirArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
            
        });
    }
    private boolean hayLlavePrimaria(LinkedList<Campos> x){
        int contador=0;
        for (Campos o : x) {
            if (o.getLlavePrimaria()==true) {
                contador++;
            }
        }
        if (contador!=0) {
            return true;
        }
        return false;
    }
    private void actualizarListaCampos() {
        DefaultListModel Listmodel;
        Listmodel = new DefaultListModel<>();
        String tempcampo = "";
        for (int i = 0; i < archivo_temp.getCampos().size(); i++) {
            tempcampo = archivo_temp.getCampos().get(i).toString();
            Listmodel.addElement(tempcampo);
        }
        jList1.setModel(Listmodel);
    }
       private void actualizarListaCampos2() {
//        DefaultListModel modelo=(DefaultListModel)jListCampos.getModel();
//        String tempcampo = "";
//        modelo.clear();
//        for (int i = 0; i < archivo_temp.getCampos().size(); i++) {
//            tempcampo = archivo_temp.getCampos().get(i).toString();
//            modelo.addElement(tempcampo);
//        }
//        jListCampos.setModel(modelo);
        DefaultListModel<String> model = (DefaultListModel<String>) jListCampos.getModel();
        model.clear(); // Limpia el modelo actual
        for (Campos campo : archivo_temp.getCampos()) {
            model.addElement(campo.toString()); // Agrega los elementos que desees mostrar
        }
        
    }
       private String devolverTipo(JComboBox com){
           String frase="";
           System.out.println(com.getSelectedIndex());
           if (com.getSelectedIndex()==0) {
                frase="Entero";
            }else if(com.getSelectedIndex()==1){
                frase="Cadena";
            }else if (com.getSelectedIndex()==2){
                frase="Double";
            }else{
                frase="Booleano";
            }
           return frase;
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Modificar;
    private javax.swing.JComboBox<String> cb_llave;
    private javax.swing.JComboBox<String> cb_modTipo;
    private javax.swing.JComboBox<String> cb_tipoCampo;
    private javax.swing.JLabel jLArchivos;
    private javax.swing.JLabel jLArchivosNombre;
    private javax.swing.JLabel jLCampos;
    private javax.swing.JLabel jLCerrar;
    private javax.swing.JLabel jLEstandarizacion;
    private javax.swing.JLabel jLIndices;
    private javax.swing.JLabel jLRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListCampos;
    private javax.swing.JMenuItem jMAbrirArchivo;
    private javax.swing.JMenuItem jMGuardarArchivo;
    private javax.swing.JMenuItem jMNuevoArchivo;
    private javax.swing.JMenuItem jMSalirArchivo;
    private javax.swing.JPanel jPA;
    private javax.swing.JPanel jPA1;
    private javax.swing.JPanel jPArchivos;
    private javax.swing.JPanel jPC;
    private javax.swing.JPanel jPE;
    private javax.swing.JPanel jPI;
    private javax.swing.JPanel jPR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenuArchivos;
    private javax.swing.JPanel jPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_agregarRegistro;
    private javax.swing.JButton jb_crearCampo;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JScrollPane jd_IntroReg;
    private javax.swing.JDialog jd_IntroRegistro;
    private javax.swing.JDialog jd_crearCampos;
    private javax.swing.JDialog jd_listarCampos;
    private javax.swing.JPanel jp_agregarCampo;
    private javax.swing.JSpinner js_ModLongitud;
    private javax.swing.JTable jt_Introd;
    private javax.swing.JMenuItem mi_BuscarRegistro;
    private javax.swing.JMenuItem mi_CrearCampo;
    private javax.swing.JMenuItem mi_EliminarRegistro;
    private javax.swing.JMenuItem mi_IntroducirRegstro;
    private javax.swing.JMenuItem mi_ListarCmpos;
    private javax.swing.JMenuItem mi_ModificarCampo;
    private javax.swing.JMenuItem mi_ModificarRegsitro;
    private javax.swing.JMenuItem mi_borrar;
    private javax.swing.JMenuItem mi_borrarCampo;
    private javax.swing.JMenuItem mi_modificarCampo;
    private javax.swing.JPopupMenu pm_Campos;
    private javax.swing.JPopupMenu pm_Registros;
    private javax.swing.JPopupMenu pm_modificar;
    private javax.swing.JTextField tf_NombreCampo;
    private javax.swing.JTextField tf_nombreCrear;
    private javax.swing.JTextField tf_tamanio;
    // End of variables declaration//GEN-END:variables

    static Archivos archivo_temp;
    LinkedList<Campos> campos;
    
 
private void nuevo_archivo() {
        JFileChooser jfc = new JFileChooser("./");

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt");
        jfc.setFileFilter(filtro);

        int result = jfc.showSaveDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File archivoSelected = jfc.getSelectedFile();
            archivo_temp = new Archivos(archivoSelected.getName(), archivoSelected.getAbsolutePath() + ".txt");
        } else if (result == JFileChooser.CANCEL_OPTION) {
            System.out.println("Se canceló la Operación.");
        }
}
private void abrirArchivo() {
        File fichero = null;
        try {
            JFileChooser jfc = new JFileChooser("./");
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt");
            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                //abre el archivo txt
                abrirArchivoTXT(fichero);

            } else if (seleccion == JFileChooser.CANCEL_OPTION) {
                System.out.println("El usuario canceló la operación.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        jLArchivosNombre.setText(archivo_temp.getNombreArchivo());
    }
private void abrirArchivoTXT(File fichero) {
        try (FileReader fr = new FileReader(fichero); BufferedReader br = new BufferedReader(fr)) {
            String linea = br.readLine();
            String[] name = fichero.getName().split("\\.");
            archivo_temp = new Archivos(name[0], fichero.getPath());
            if (linea != null) {
                String[] token = linea.split("\\|");
                try {
                    archivo_temp.setCamposOpen(token[2]);
                } catch (ArrayIndexOutOfBoundsException e) {
                    System.out.println("NO hay campos");
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.out.println("ABRIO EL ARCHIVO");
    }
public void guardararchivo() {
        try {
            guarArchivoTXT();

        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente");
    }
private void guarArchivoTXT() throws IOException {
        String[] lineas = new String[99999];
  
        //metadata
        StringBuilder txt = new StringBuilder();
        try {
            txt.append(archivo_temp.getCamposClose());
        } catch (Exception e) {
            System.out.println("3");
            //e.printStackTrace();
        }
        lineas[0] = txt.toString();
        //fin metadata
        try {
            FileWriter fw = new FileWriter(archivo_temp.getPath());
            BufferedWriter bw = new BufferedWriter(fw);
            for (int i = 0; i < archivo_temp.getCampos().size() + 1; i++) {
                System.out.println(lineas[i]);
                bw.write(lineas[i]);
                bw.newLine();
            }
            bw.close();
        } catch (Exception e) {
            System.out.println("4");
            e.printStackTrace();
        }

    }
    private void cerrarArchivo() {
        archivo_temp = null;
        
    }
//public void agregarElementoAvailList(Nodo nuevoNodo){
//    listaEnlazada.addFirst(nuevoNodo);
//}
//public void guardarAvailList(LinkedList<Nodo> lista, String archivo) {
//        try (ObjectOutputStream stream = new ObjectOutputStream(new FileOutputStream(archivo))) {
//            for (Nodo nodo : lista) {
//                stream.writeObject(nodo);
//            }
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//}
//public LinkedList<Nodo> leerAvailList(String archivo) {
//        LinkedList<Nodo> lista = new LinkedList<>();
//        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream(archivo))) {
//            while (true) {
//                try {
//                    Nodo nodo = (Nodo) in.readObject();
//                    lista.add(nodo);
//                } catch (EOFException e) {
//                    break; // Fin del archivo
//                }
//            }
//        } catch (IOException | ClassNotFoundException e) {
//            e.printStackTrace();
//        }
//        return lista;
//        
//}
//
//private void guardarMetadata() {
//    // Asumimos que 'archivo_temp' es un objeto de la clase Archivos con la ruta y nombre del archivo
//    if (archivo_temp != null) {
//        // Crea el Metadata con el autor y el availList
//        Metadata metadata = new Metadata("Autor Ejemplo", listaEnlazada);  // listaEnlazada es el availList
//
//        // Guardar la metadata en un archivo
//        metadata.guardarMetadata(archivo_temp.getPath() + ".meta");  // Guarda en un archivo con extensión .meta
//    }
//}
}


